<?php

namespace SF\AbreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatoGeograficoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatoGeograficoRepository extends EntityRepository
{
}
