<?php

namespace SF\AbreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetalleProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleProyectoRepository extends EntityRepository
{
}
